name: Build Android

on:
  [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        arch: [ "aarch64" ]
      fail-fast: false

    name: "Build"

    runs-on: ubuntu-latest
    env:
      ANDROID_NDK_HOME: "${ANDROID_SDK_ROOT}/ndk-bundle"

    steps:
      - uses: actions/checkout@main

      - name: Build
        run: |
          sudo apt update
          sudo apt install -y meson libxrandr-dev libxxf86vm-dev libxcb-*-dev libx11-xcb-dev libxfixes-dev libx11-dev
          cp -R /usr/include/X11 include/
          cp -R /usr/include/xcb include/
          
          pip3 install mako
          envsubst < android-cross >build-crossfile
          git clone --depth 1 https://gitlab.freedesktop.org/mesa/drm.git
          cd drm
          meson setup "build-android" \
            --prefix=/tmp/build \
            --native-file="../build-crossfile" \
            --cross-file "../build-crossfile" \
            -Ddefault_library=static \
            --wrap-mode=nofallback \
            -Dintel=disabled \
            -Dradeon=disabled \
            -Damdgpu=disabled \
            -Dnouveau=disabled \
            -Dvmwgfx=disabled \
            -Dfreedreno=disabled \
            -Dvc4=disabled \
            -Detnaviv=disabled \
           -Dfreedreno-kgsl=false
          meson compile -C "build-android" -j 4
          meson install -C "build-android"

          cd ..
          envsubst < android-cross >build-crossfile
          meson setup "build-android" \
            --prefix=/tmp/build \
            --wrap-mode=nofallback \
            -Dforce_fallback_for=llvm \
            -Dosmesa=true \
            --native-file="build-crossfile" \
            --cross-file "build-crossfile" \
            --buildtype release \
            -Dplatforms=android \
            -Dplatform-sdk-version=26 \
            -Dandroid-stub=true \
            -Dllvm=disabled \
            -Dshared-llvm=disabled \
            -Dxlib-lease=disabled \
            -Degl=enabled \
            -Dgbm=disabled \
            -Dopengl=true \
            -Dvulkan-drivers= \
            -Dprecomp-compiler=system \
            -Dgallium-drivers=virgl
          meson compile -C "build-android" -j 4
          meson install -C "build-android"
      - name: Upload libraries
        uses: actions/upload-artifact@main
        with:
          name: libmesa_${{matrix.arch}}
          path: /tmp/build
